name: Build APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Download gradle-wrapper.jar
      run: |
        cd gradle/wrapper
        wget https://github.com/gradle/gradle/raw/v7.5.0/gradle/wrapper/gradle-wrapper.jar
        cd ../..
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    
    - name: Clean build
      run: ./gradlew clean --no-daemon --stacktrace
    
    - name: Build Debug APK
      run: ./gradlew assembleDebug --no-daemon --stacktrace